services:
  izacdotcomapi:
    build:
      context: /home/ubuntu/izacdotcomapi
      dockerfile: /home/ubuntu/infra/compose/izacdotcomapi/Dockerfile
    restart: unless-stopped
    env_file: /home/ubuntu/izacdotcomapi/.env
    ports:
      - "8080:8080"
